<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guestbook.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GuestBookList</code>
 */
class GuestBookList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .GuestBook guestbook = 1;</code>
     */
    private $guestbook;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \GuestBook[]|\Google\Protobuf\Internal\RepeatedField $guestbook
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guestbook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .GuestBook guestbook = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGuestbook()
    {
        return $this->guestbook;
    }

    /**
     * Generated from protobuf field <code>repeated .GuestBook guestbook = 1;</code>
     * @param \GuestBook[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGuestbook($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GuestBook::class);
        $this->guestbook = $arr;

        return $this;
    }

}

