<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto

namespace GPBMetadata;

class Greet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3010a0b67726565742e70726f746f120e70726f746f6275662e677265" .
            "6574221c0a0c48656c6c6f52657175657374120c0a046e616d6518012001" .
            "2809221d0a0a48656c6c6f5265706c79120f0a076d657373616765180120" .
            "012809324f0a074772656574657212440a0853617948656c6c6f121c2e70" .
            "726f746f6275662e67726565742e48656c6c6f526571756573741a1a2e70" .
            "726f746f6275662e67726565742e48656c6c6f5265706c79620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

