<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guestbook.proto

namespace GPBMetadata;

class Guestbook
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d020a0f6775657374626f6f6b2e70726f746f121270726f746f627566" .
            "2e6775657374626f6f6b22370a094775657374426f6f6b120a0a02696418" .
            "0120012809120d0a05656d61696c180220012809120f0a07636f6d6d656e" .
            "7418032001280922070a05456d70747922400a0d4775657374426f6f6b4c" .
            "697374122f0a086775657374626f6f18012003280b321d2e70726f746f62" .
            "75662e6775657374626f6f6b2e4775657374426f6f6b325a0a1047756573" .
            "74426f6f6b5365727669636512460a044c69737412192e70726f746f6275" .
            "662e6775657374626f6f6b2e456d7074791a212e70726f746f6275662e67" .
            "75657374626f6f6b2e4775657374426f6f6b4c6973742200620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

