<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guestbook.proto

namespace Protobuf\Guestbook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.guestbook.Empty</code>
 */
class PBEmpty extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Protobuf\Metadata\Guestbook::initOnce();
        parent::__construct($data);
    }

}

