<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guestbook.proto

namespace Protobuf\Guestbook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuf.guestbook.GuestBookList</code>
 */
class GuestBookList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protobuf.guestbook.GuestBook guestboo = 1;</code>
     */
    private $guestboo;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protobuf\Guestbook\GuestBook[]|\Google\Protobuf\Internal\RepeatedField $guestboo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guestbook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.guestbook.GuestBook guestboo = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGuestboo()
    {
        return $this->guestboo;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuf.guestbook.GuestBook guestboo = 1;</code>
     * @param \Protobuf\Guestbook\GuestBook[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGuestboo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuf\Guestbook\GuestBook::class);
        $this->guestboo = $arr;

        return $this;
    }

}

